---

version: '3'
services:
    centos6:
        environment:
            - CONSULVER
            - TEMPLATEVER
        build:
            context: .
            dockerfile: ./docker/centos6/Dockerfile
        volumes:
            - ../centos6:/RPMS

    centos7:
        environment:
            - CONSULVER
            - TEMPLATEVER
        build:
            context: .
            dockerfile: ./docker/centos7/Dockerfile
        volumes:
            - ../centos7:/RPMS

    amzn2018:
        environment:
            - CONSULVER
            - TEMPLATEVER
        build:
            context: .
            dockerfile: ./docker/centos7/Dockerfile
        volumes:
            - ../amzn2018:/RPMS
